# Generated by Django 2.1.3 on 2018-11-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='current date'),
        ),
    ]
